### ISSUE TITLE
Why not read the 4th edition?

### ISSUE THREAD

**Issue by ghost** [luqmanmalik/CPL#1]
Why not read the 4th edition?

**Comment by luqmanmalik** [comment]
Hi,

3rd edition is freely available, and I'm (purely) working through it for academic interest. Are you reading / have you read 4E?

Best,

Luq

**Comment by ghost** [comment]
Yes, I'm reading the 4th edition. This is the newest edition, and it introduces C++11. C++11 is very powerful, so I think it's better.

**Comment by luqmanmalik** [comment]
Noted.
